services:
  - type: web
    name: sovereign-ai-commerce-backend
    env: go
    region: frankfurt
    plan: free
    buildCommand: go build -o server main.go
    startCommand: ./server
    envVars:
      - key: GO_VERSION
        value: 1.22.5
      - key: PORT
        value: 8000
      - key: GROQ_API_KEY
        sync: false
      - key: CEREBRAS_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: MISTRAL_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: CF_ACCOUNT_ID
        sync: false
      - key: CF_API_TOKEN
        sync: false
      - key: EVOLUTION_API_URL
        value: https://evolution-api-latest-gxue.onrender.com
      - key: EVOLUTION_API_KEY
        value: F84B4F845BC6-464A-AD0E-553FD1046981
